# 데이터프레임


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
x = x.reshape(6,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
# df = pd.DataFrame(x)
df = pd.DataFrame(x, columns=['A', 'B', 'C', 'D'])
df

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23

In [38]:
df['D'] <12

0     True
1     True
2     True
3    False
4    False
5    False
Name: D, dtype: bool

In [39]:
df[df['D'] <12]

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [40]:
df

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23

In [41]:
df['E'] = 50
df

A   B   C   D   E
0   0   1   2   3  50
1   4   5   6   7  50
2   8   9  10  11  50
3  12  13  14  15  50
4  16  17  18  19  50
5  20  21  22  23  50

In [42]:
df['E'] = [4,3,5,6,8,2]
df

A   B   C   D  E
0   0   1   2   3  4
1   4   5   6   7  3
2   8   9  10  11  5
3  12  13  14  15  6
4  16  17  18  19  8
5  20  21  22  23  2

In [43]:
df[0:4]

A   B   C   D  E
0   0   1   2   3  4
1   4   5   6   7  3
2   8   9  10  11  5
3  12  13  14  15  6

In [44]:
df.loc[0:4]

A   B   C   D  E
0   0   1   2   3  4
1   4   5   6   7  3
2   8   9  10  11  5
3  12  13  14  15  6
4  16  17  18  19  8

In [47]:
df.iloc[0:4]

A   B   C   D  E
0   0   1   2   3  4
1   4   5   6   7  3
2   8   9  10  11  5
3  12  13  14  15  6

In [49]:
df = df.drop('E', axis=1)
df

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23

In [50]:
df.sum()

A    60
B    66
C    72
D    78
dtype: int64

In [51]:
df.sum(axis=1)

0     6
1    22
2    38
3    54
4    70
5    86
dtype: int64

In [52]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [53]:
X = df.values
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
X[:,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [56]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])